name: Validate contracts.json

on:
  pull_request:
    paths:
      - 'contracts.json'
      - 'README.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install jq
        run: sudo apt-get install -y jq
          
      - name: Validate contracts.json and verify README.md
        run: bash convert.sh