name: Verify Code IDs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'contracts.json'
      - 'scripts/verify-code-ids.js'
      - '.github/workflows/verify-code-ids.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Verify Code IDs
        run: node scripts/verify-code-ids.js
